import { Model, DataTypes, CreationOptional, Optional } from 'sequelize';
import { sequelize } from '../config';

interface UserRoleAttributes {
  id: number;
  user_id: string;
  role: string;
}

// id is auto-generated, so it's optional for creation
interface UserRoleCreationAttributes extends Optional<UserRoleAttributes, 'id'> {}

class UserRole extends Model<UserRoleAttributes, UserRoleCreationAttributes> implements UserRoleAttributes {
  public id!: number;
  public user_id!: string;
  public role!: string;
}

UserRole.init({
  id: {
    type: DataTypes.BIGINT, // Changed to BIGINT to match SQL 'bigint generated by default as identity'
    autoIncrement: true,    // Added autoIncrement
    primaryKey: true,
  },
  user_id: {
    type: DataTypes.UUID,
    allowNull: false,
    unique: true,
  },
  role: {
    type: DataTypes.STRING,
    defaultValue: 'user',
  },
}, {
  sequelize,
  tableName: 'user_roles',
  timestamps: false,
  underscored: true,
});

export default UserRole;
